bin_props:
  bin_1:
    name: bin_1_part_5
    part_id: 05_MBRFA30-2-P6
    mask_id: 1
  bin_2:
    name: bin_1_part_16
    part_id: 16_SPWF6
    mask_id: 2
  bin_3:
    name: bin_1_part_17
    part_id: 17_SCB4-10
    mask_id: 3
  bin_4:
    name: bin_2_part_4
    part_id: 04_37D-GEARMOTOR-50-70
    mask_id: 4
  bin_5:
    name: bin_2_part_7
    part_id: 07_SBARB6200ZZ_30
    mask_id: 5
  bin_6:
    name: bin_2_part_8
    part_id: 08_KZAF1075NA4WA55GA20AA0
    mask_id: 6

part_props:
  04_37D-GEARMOTOR-50-70:
    name: Geared motor
    robot_name: b_bot
    camera_name: a_phoxi_m_camera
    destination: tray_1_partition_4
  05_MBRFA30-2-P6:
    name: Pully for round belt
    robot_name: b_bot
    camera_name: a_phoxi_m_camera
    destination: tray_2_partition_6
  06_MBT4-400:
    name: Polyurethane round belt
    robot_name: b_bot
    camera_name: a_phoxi_m_camera
    destination: tray_1_partition_3
  07_SBARB6200ZZ_30:
    name: Bearing with housing
    robot_name: b_bot
    camera_name: a_phoxi_m_camera
    destination: tray_1_partition_2
  08_KZAF1075NA4WA55GA20AA0:
    name: Drive shaft
    robot_name: b_bot
    camera_name: a_phoxi_m_camera
    destination: tray_2_partition_1
  09_EDCS10:
    name: End cap for shaft
    robot_name: a_bot
    camera_name: a_phoxi_m_camera
    destination: tray_2_partition_4
  10_CLBPS10_17_4:
    name: Bearing spacers for inner ring
    robot_name: a_bot
    camera_name: a_phoxi_m_camera
    destination: tray_2_partition_7
  11_MBRAC60-2-10:
    name: Pully for round belts clamping
    robot_name: b_bot
    camera_name: a_phoxi_m_camera
    destination: tray_1_partition_1
  12_CLBUS6-9-9.5:
    name: Bearing spacer for inner ring
    robot_name: b_bot
    camera_name: a_phoxi_m_camera
    destination: tray_2_partition_3
  13_MBGA30-2:
    name: Idler for round belt
    robot_name: b_bot
    camera_name: a_phoxi_m_camera
    destination: tray_1_partition_5
  14_BGPSL6-9-L30-F8:
    name: Bearing shaft screw
    robot_name: a_bot
    camera_name: a_phoxi_m_camera
    destination: tray_2_partition_2
  15_SLBNR6:
    name: M6 hex nut
    robot_name: a_bot
    camera_name: a_phoxi_m_camera
    destination: tray_2_partition_5
  16_SPWF6:
    name: M6 flat washer
    robot_name: a_bot
    camera_name: a_phoxi_m_camera
    destination: tray_2_partition_8
  17_SCB4-10:
    name: M4 head cap screw
    robot_name: a_bot
    camera_name: a_phoxi_m_camera
    destination: skrewholder_1
  18_SCB3-10:
    name: M3 head cap screw
    robot_name: a_bot
    camera_name: a_phoxi_m_camera
    destination: skrewholder_2

picking_parameters:
  04_37D-GEARMOTOR-50-70:
    approach_offset: [0.0, 0.0, 0.15]
    grasp_offset: [0.0, 0.0, 0.001]
    place_offset: [0.0, 0.0, 0.06]
    liftup_after: true
    speed_fast: 1.0
    speed_slow: 0.1
  05_MBRFA30-2-P6:
    approach_offset: [0.0, 0.0, 0.15]
    grasp_offset: [0.0, 0.0, 0.001]
    place_offset: [0.0, 0.0, 0.03]
    liftup_after: true
    speed_fast: 1.0
    speed_slow: 1.0
  06_MBT4-400:
    approach_offset: [0.0, 0.0, 0.15]
    grasp_offset: [0.0, 0.0, 0.0]
    place_offset: [0.0, 0.0, 0.05]
    liftup_after: true
    speed_fast: 1.0
    speed_slow: 1.0
  07_SBARB6200ZZ_30:
    approach_offset: [0.0, 0.0, 0.15]
    grasp_offset: [0.0, 0.0, 0.001]
    place_offset: [0.0, 0.0, 0.05]
    liftup_after: true
    speed_fast: 1.0
    speed_slow: 0.1
  08_KZAF1075NA4WA55GA20AA0:
    approach_offset: [0.0, 0.0, 0.15]
    grasp_offset: [0.0, 0.0, 0.00]
    place_offset: [0.0, 0.0, 0.03]
    liftup_after: true
    speed_fast: 1.0
    speed_slow: 0.1
  09_EDCS10:
    approach_offset: [0.0, 0.0, 0.15]
    grasp_offset: [0.0, 0.0, -0.002]
    place_offset: [0.0, 0.0, 0.05]
    liftup_after: true
    speed_fast: 1.0
    speed_slow: 1.0
  10_CLBPS10_17_4:
    approach_offset: [0.0, 0.0, 0.15]
    grasp_offset: [0.0, 0.0, -0.002]
    place_offset: [0.0, 0.0, 0.05]
    liftup_after: true
    speed_fast: 1.0
    speed_slow: 1.0
  11_MBRAC60-2-10:
    approach_offset: [0.0, 0.0, 0.15]
    grasp_offset: [0.0, 0.0, -0.001]
    place_offset: [0.0, 0.0, 0.05]
    liftup_after: true
    speed_fast: 1.0
    speed_slow: 0.04
  12_CLBUS6-9-9.5:
    approach_offset: [0.0, 0.0, 0.15]
    grasp_offset: [0.0, 0.0, 0.0]
    place_offset: [0.0, 0.0, 0.05]
    liftup_after: true
    speed_fast: 1.0
    speed_slow: 0.04
  13_MBGA30-2:
    approach_offset: [0.0, 0.0, 0.15]
    grasp_offset: [0.0, 0.0, -0.001]
    place_offset: [0.0, 0.0, 0.05]
    speed_fast: 1.0
    speed_slow: 0.04
  14_BGPSL6-9-L30-F8:
    approach_offset: [0.0, 0.0, 0.15]
    grasp_offset: [0.0, 0.0, -0.002]
    place_offset: [0.0, 0.0, 0.05]
    liftup_after: true
    speed_fast: 1.0
    speed_slow: 1.0
  15_SLBNR6:
    approach_offset: [0.0, 0.0, 0.15]
    grasp_offset: [0.0, 0.0, -0.002]
    place_offset: [0.0, 0.0, 0.05]
    liftup_after: true
    speed_fast: 1.0
    speed_slow: 1.0
  16_SPWF6:
    approach_offset: [0.0, 0.0, 0.15]
    grasp_offset: [0.0, 0.0, -0.002]
    place_offset: [0.0, 0.0, 0.05]
    liftup_after: true
    speed_fast: 1.0
    speed_slow: 1.0
  17_SCB4-10:
    approach_offset: [0.0, 0.0, 0.15]
    grasp_offset: [0.0, 0.0, -0.002]
    place_offset: [0.0, 0.0, 0.05]
    liftup_after: true
    speed_fast: 1.0
    speed_slow: 1.0
  18_SCB3-10:
    approach_offset: [0.0, 0.0, 0.15]
    grasp_offset: [0.0, 0.0, -0.002]
    place_offset: [0.0, 0.0, 0.05]
    liftup_after: true
    speed_fast: 1.0
    speed_slow: 1.0

graspability_parameters:
  04_37D-GEARMOTOR-50-70:
    ns: 2
    nz: 0.7
    object_size: 15
    min_distance: 30
    contact_radius: 8
    open_width: 100
    finger_width: 1
    finger_thickness: 5
    insertion_depth: 0.020
  05_MBRFA30-2-P6:
    ns: 2
    nz: 0.7
    object_size: 8
    min_distance: 30
    contact_radius: 6
    open_width: 45
    finger_width: 1
    finger_thickness: 5
    insertion_depth: 0.003
  06_MBT4-400:
    ns: 2
    nz: 0.7
    object_size: 2
    min_distance: 30
    contact_radius: 2
    open_width: 20
    finger_width: 1
    finger_thickness: 5
    insertion_depth: 0.005
  07_SBARB6200ZZ_30:
    ns: 2
    nz: 0.7
    object_size: 12
    min_distance: 30
    contact_radius: 12
    open_width: 20
    finger_width: 1
    finger_thickness: 5
    insertion_depth: 0.005
  08_KZAF1075NA4WA55GA20AA0:
    ns: 0
    detect_edge: false
    object_size: 4
    min_distance: 30
    contact_radius: 2
    open_width: 20
    finger_width: 1
    finger_thickness: 5
    insertion_depth: 0.004
  09_EDCS10:
    ns: 2
    nz: 0.7
    object_size: 3
    min_distance: 30
    contact_radius: 3
    open_width: 20
    finger_width: 1
    finger_thickness: 5
    insertion_depth: 0.001
  10_CLBPS10_17_4:
    ns: 2
    nz: 0.7
    object_size: 3
    min_distance: 30
    contact_radius: 3
    open_width: 20
    finger_width: 1
    finger_thickness: 5
    insertion_depth: 0.001
  11_MBRAC60-2-10:
    ns: 2
    nz: 0.7
    object_size: 12
    min_distance: 30
    contact_radius: 12
    open_width: 20
    finger_width: 1
    finger_thickness: 5
    insertion_depth: 0.001
  12_CLBUS6-9-9.5:
    ns: 2
    nz: 0.7
    object_size: 4
    min_distance: 30
    contact_radius: 2
    open_width: 20
    finger_width: 1
    finger_thickness: 5
    insertion_depth: 0.001
  13_MBGA30-2:
    ns: 2
    nz: 0.7
    object_size: 7
    min_distance: 30
    contact_radius: 2
    open_width: 30
    finger_width: 1
    finger_thickness: 5
    insertion_depth: 0.001
  14_BGPSL6-9-L30-F8:
    ns: 0
    nz: 0.7
    object_size: 4
    min_distance: 30
    contact_radius: 2
    open_width: 14
    finger_width: 1
    finger_thickness: 5
    insertion_depth: 0.005
  15_SLBNR6:
    ns: 2
    nz: 0.7
    object_size: 3
    min_distance: 30
    contact_radius: 3
    open_width: 20
    finger_width: 1
    finger_thickness: 5
    insertion_depth: 0.001
  16_SPWF6:
    ns: 0
    nz: 0.7
    object_size: 3
    min_distance: 30
    contact_radius: 3
    open_width: 15
    finger_width: 1
    finger_thickness: 5
    insertion_depth: 0.001
  17_SCB4-10:
    ns: 0
    nz: 0.7
    object_size: 1
    min_distance: 30
    contact_radius: 1
    open_width: 10
    finger_width: 1
    finger_thickness: 5
    insertion_depth: 0.001
  18_SCB3-10:
    ns: 0
    nz: 0.7
    object_size: 1
    min_distance: 30
    contact_radius: 1
    open_width: 10
    finger_width: 1
    finger_thickness: 5
    insertion_depth: 0.001
